# Generated by Django 2.1.2 on 2018-10-30 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='raza',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='descripcion',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='nombre',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
